### ISSUE TITLE
Examples folder

### ISSUE THREAD

**Issue by britanik** [dzarezenko/coinmarketcap-api#1]
Sure, this project is not rocket science, but if you referencing Examples folder on main page, then you should put it somewhere in repo )

**Comment by dzarezenko** [comment]
Do you need some specific examples? I'll add them step-by-step by request.

**Comment by 2ge** [comment]
There is no need for specific examples, but in your readme:

"Usage: You can find usage examples in the examples/ folder."

examples folder is missing. Either remove it from Readme, or add super simple example there.
